image: node:12.15
before_script:
  - set -xe
stages:
  - prepare
  - build
  - test
  - deploy
cache:
  paths:
    - node_modules/
install_dependencies:
  stage: prepare
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
build:
  stage: build
  script:
  # this token expires every day anyway
    - npm run publish:config -- jQap7WB6y5JC0ymzzz4mWHDmQvmjLmE0CRFXbtf1Fw1Pnef8Qnp5gdTZcw9/jAOR
    - npm run prepublish:version
    - npm run build
  artifacts:
    paths:
      - dist/
  only:
    - master
  tags:
    - docker
test:
  stage: test
  script:
    - npm run test
  only:
    - master
  tags:
    - docker
deploy-api:
  stage: deploy
  script:
    - npm run publish:gitlab-ci
  only:
    - master
  tags:
    - docker
    
