image: node:12.15
before_script:
  - set -xe
stages:
  - prepare
  - build
  - test
  - deploy
cache:
  paths:
    - node_modules/
install_dependencies:
  stage: prepare
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
build:
  stage: build
  script:
    - npm run prepublish:version
    - npm run build
  artifacts:
    paths:
      - dist/
      - package.json
  only:
    - master
  tags:
    - docker
test:
  stage: test
  script:
    - npm run test
  only:
    - master
  tags:
    - docker
deploy-api:
  stage: deploy
  script:
 # this token expires every day anyway
    - npm run publish:config
    - npm publish --access public
  only:
    - master
  tags:
    - docker
    
